Started working on the admin dashboard. Added admin controller and model
aaronmyatt/rails-quiz-flow pull request #5
Opened 2018-12-28 09:14 UTC by ProsperMindvalley

2019-01-04 04:04 UTC, aaronmyatt requested changes

2019-01-04 04:04 UTC, aaronmyatt commented on app/views/category_admin/_table.html.erb
> +          <button class="button is-success"><%= link_to "Add Category", "new", id: 'link-color' %></button>
need to fix the url here `new` should point to `category_admin/new`

2019-01-04 04:04 UTC, aaronmyatt commented on app/views/drilldown_admin/_table.html.erb
> +          <button class="button is-success"><%= link_to "Add Category", "new", id: 'link-color' %></button>
fix the path here too, `new` fails

2019-01-04 04:05 UTC, aaronmyatt commented
@ProsperMindvalley @pavi304 we definitely want to fix the layout stuff too. It's getting quite messy seeing all that repeated code.

2019-01-07 04:04 UTC, prosperityk commented on app/controllers/category_admin_controller.rb
> +  def show
Remove me

2019-01-07 04:04 UTC, prosperityk commented on app/controllers/drilldown_controller.rb
> +      # session[:category].each do |category|
Remove all these comments

2019-01-07 04:04 UTC, prosperityk commented on app/controllers/questions_controller.rb
> +    # question=[]
Please Remove Me

2019-01-07 04:04 UTC, ProsperMindvalley commented on app/views/layouts/application.html.erb
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
Use Gem for this

2019-01-07 04:07 UTC, merged

2019-01-07 06:25 UTC, pavikunusilin commented on app/controllers/drilldown_controller.rb
> +      # session[:category].each do |category|
done.

2019-01-07 06:26 UTC, pavikunusilin commented on app/controllers/questions_controller.rb
> +    # question=[]
done.