Have removed sessions in Category, Drilldown and Question Controllers
aaronmyatt/rails-quiz-flow pull request #6
Opened 2019-01-08 03:06 UTC by ProsperMindvalley

2019-01-08 16:23 UTC, aaronmyatt requested changes

2019-01-08 16:23 UTC, aaronmyatt commented on app/controllers/home_controller.rb
>      session[:user]=user.id
So, for your information, it is definitely good practice to keep a reference to the user in the session, but we can abstract this sort of common pattern into helpers, here's how MV Home is doing it: https://github.com/mindvalley/MVA_Home/blob/fdffdd751b43519d2cdafd8ecf7d7bf61903dab4/app/helpers/auth0_helper.rb

We can do the same once we implement authentication.

2019-01-08 16:23 UTC, aaronmyatt commented on app/controllers/questions_controller.rb
> +    question_session = params[:questions]
Can we rename this variable?, maybe `question_params`?

2019-01-08 16:23 UTC, aaronmyatt commented on app/controllers/recommendation_controller.rb
> +    @category = Category.last(4).pluck(:name)
So, this isn't gonna work for us in the long term. Eventually there will be two people who perform the quiz at the same time, someone will see the wrong data.

Let's update the backlog with a ticket to connect the cateogry, drilldown and question choices to the users email

2019-01-08 16:23 UTC, aaronmyatt commented on app/views/category/index.html.erb
> +         <%= check_box_tag "category[]", x.name  %>
rename the `x` please

2019-01-08 16:24 UTC, aaronmyatt commented
All in all, really great, let's tidy some of the parameter naming, and also gave a little food for thought,.

2019-01-09 05:29 UTC, pavikunusilin commented on app/controllers/questions_controller.rb
> +    question_session = params[:questions]
DONE.

2019-01-09 05:30 UTC, pavikunusilin commented on app/views/category/index.html.erb
> +         <%= check_box_tag "category[]", x.name  %>
DONE.

2019-01-10 03:32 UTC, merged